import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import CreateTodoForm from "~/components/CreateTodoForm";


const createTodo: NextPage = () => {
    // const test = api.example.getAll.useQuery()
  
    return (
      <>
        <Head>
          <title>Create Todo</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create Todo
            </h1>
            <div>
            <CreateTodoForm />
            </div>
            <button
              className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
            >
            <Link href="/">Home</Link>
            </button>
        </main>
      </>
    );
  };
  
  export default createTodo;